### ISSUE TITLE
Regions replace does not work in regions API

### ISSUE THREAD

**Issue by peterdesmet** [c3js/c3#1255]
The [regions API](http://c3js.org/reference.html#api-regions) has a method for replacing regions:

```JS
chart.regions([
  {axis: 'x', start: 5, class: 'regionX'},
  {axis: 'y', end: 50, class: 'regionY'}
]);
```

In practice, this only seems to work for initializing a region (cf. `regions.add()`), but not updating a region. E.g. in [this fiddle](http://jsfiddle.net/10ktt85p/), the first setTimeOut function will set a region, the second one does nothing.

**Comment by aendrew** [comment]
Confirming — just ran into this myself. Currently working around it using chart.regions.remove() followed by repopulating using chart.regions in a setTimeout.

**Comment by aendrew** [comment]
Adding `tests` label — there should be a unit test that would have prevented this bug. Either the existing test is broken or an adequate test does not yet exist.

**Comment by aendrew** [comment]
Investigated this a bit further — it isn't a regressive bug, *because chart.region has never actually worked*. I've tried back as far as version 0.3.0 and I can't get `chart.region` to behave as it should in any version.

PR forthcoming, I need this fixed literally tonight.

**Comment by peterdesmet** [comment]
Thanks for testing. Can't wait to use this.

**Comment by aendrew** [comment]
Haven't been able to figure this out yet, but have been able to best work around it by calling `chart.destroy()` followed by a new `chart.generate()`.

**Comment by peterdesmet** [comment]
Since I want to use the regions API to respond to a user clicking on the chart, I can't use `chart.destroy()`. I also tried `regions.remove()`, followed by `regions.add()`, which works, but not on fast clicking back and forth on the chart. So, in the meantime, I'm using two gridlines to indicate the region: not perfect, but it does the job.

**Comment by sentient** [comment]
This is what I do. I set the new regions with a 500ms delay and a graph.flush()

```
        var setNewRegions = function(){ chartSpO2.regions([{
              axis: 'y',
              end:  $scope.mod.SpO2.settings.danger,
              class: 'region-danger'
            }, {
              //Low but no panic yet
              axis: 'y',
              start: $scope.mod.SpO2.settings.danger,
              end: $scope.mod.SpO2.settings.warning,
              class: 'region-warn'
            }, {
              axis: 'y',
              start: $scope.mod.SpO2.settings.warning,
              class: 'region-info'
            }
          ]);
          chartSpO2.flush();
        };

          chartSpO2.regions([]);
          $timeout(setNewRegions, 500);
```

**Comment by eightyeight** [comment]
I'm using @sentient's approach and it works, though it's annoying. It doesn't appear to work with a smaller timeout, which makes me wonder if somehow the chart's animation is killing the regions during rendering.

**Comment by masayuki0812** [comment]
I think this has been fixed. There was a bug that data of `rect` in region `g` is not updated even if new region data given.

**Comment by masayuki0812** [comment]
Let me close this for the moment and please reopen if something is wrong.

**Comment by martingraham** [comment]
You can push the g parent elements data down to the rect element by doing .select rather than .selectAll (it's a little-known d3 effect that often causes errors rather than solves them)

Since there's only 1 rect per group element there's no problem with not using .selectAll

```
        regions = $$.mainRegion.selectAll('rect').each(function () {
            // data is binded to g and it's not transferred to rect (child node) automatically,
            // then data of each rect has to be updated manually.
            // TODO: there should be more efficient way to solve this?
            var parentData = $$.d3.select(this.parentNode).datum();
            $$.d3.select(this).datum(parentData);
        }),
```
becomes
                   `                 regions = $$.mainRegion.select('rect'),`

**Comment by pabloschiavini** [comment]
I just re-tested with the latest version and the problem persists.
I was able to reproduce the problem using the example website https://c3js.org/samples/region.html and the following code:

var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30, 200, 100, 400, 150, 250, 400],
            ['data2', 830, 1200, 1100, 1400, 1150, 1250, 1500],
        ],
        axes: {
            data2: 'y2'
        }
    },
    axis: {
        y2: {
            show: true
        }
    },
    regions: [
        {axis: 'x', start: 2, end: 4, class: 'regionX'},
    ]
});

setTimeout(() => {
    chart.regions(
        [{axis: 'x', start: 3, end: 5, class: 'regionY'}]);
}, 1000);

Workaround: Running chart.regions.remove({class: ['regionX']}) before "setTimeout" seems to work, but only for large timeouts. From usability point of view, it's quite anoying.

**Comment by dao-phuong** [comment]
@masayuki0812  I also have the same problem with regions API at lastest version. Can you open this issue again

**Comment by drewkiimon** [comment]
Having this problem still as well.
