### ISSUE TITLE
Multiple series on category axis not working

### ISSUE THREAD

**Issue by rlindner81** [c3js/c3#1643]
When using multiple series, i.e., the data.xs option and an axis in category mode two things are not as expected:

1. if the second series defines more points than the first, they are not named correctly on the axis, but replaced with numbers
2. if the second series changes the order of category names for the second set of data points, this change is ignored

DEMO:
http://jsfiddle.net/Lcwh2tno/1/
```javascript
var chart = c3.generate({
  data: {
    xs: {
      data1: "cat1",
      data2: "cat2",
    },
    columns: [
      ["cat1", "a", "b", "c", "d"],
      ["data1", 30, 200, 100, 400],
      ["cat2", "b", "a", "c", "d", "e", "f"],
      ["data2", 400, 60, 200, 800, 10, 10]
    ]
  },
  axis: {
    x: {
      type: "category"
    }
  }
});
```

**Comment by abacaj** [comment]
If you flip your categories - specifically so that the longest dataset is the first of the categories like so:

http://jsfiddle.net/Lcwh2tno/1/
```
var chart = c3.generate({
  data: {
    xs: {
      'data1': 'x1',
      'data2': 'x2',
    },
    columns: [
      ['x1', 'a', 'b', 'c', 'd', 'e', 'f'],
      ['x2', 'a', 'b', 'c', 'd', 'e'],
      ['data1', 30, 200, 100, 400, 150, 250],
      ['data2', 20, 180, 240, 100, 190]
    ]
  },
  axis: {
    x: {
      type: "category"
    }
  }
});
```

**Comment by rlindner81** [comment]
Hi @abacaj, thanks for your ideas. 

Let me be a bit overly critical, so you can see my later point better: Rearranging rows and columns of the datasets can get you only so far. Imagine, for example, you wanted to show two datasets with only a small overlap, one ranging from a--d and another from c--f. Also switching to an indexed type would not be acceptable for some usecases, since it really changes the information that is ultimately displayed in the chart.

Now for my real point: I think these workarounds would cover a lot of cases, but they should not be necessary imo. You could invest practically the same development work that is required to convert the data into the formats you suggest and just make c3 itself more versatile and handle the data as it comes in. 

I actually have a fix in mind that will make categories work well for all cases that I can think of. If you are curious, be sure to stay tuned.

**Comment by abacaj** [comment]
@rlindner81 to be honest I don't think your PR will get through. I was contemplating forking c3js.

**Comment by rlindner81** [comment]
@abacaj I don't really expect the PR to be merged, but maybe some other forkers will pick it up... it's too bad this library is no longer being actively developed. I think it has a good mix of performance and features. I hope someone will pick up the torch and carry on C3...

**Comment by aendrew** [comment]
I've merged #1650 into the `dev` branch. Marking as "resolved maybe", closing once that fix lands in `master`. Thanks for the help! 😄

**Comment by jnehlmeier** [comment]
Hmm what if categories do not overlap at all? My use case is like:
```
var chart = c3.generate({
    data: {
        xs: {
            'Room 1.1': 'x1', // should be under Building 1
            'Room 1.2': 'x1',
            'Room 2.1': 'x2', // should be under Building 2
            'Room 2.2': 'x2',
            'Room 2.3': 'x2',
            'Room 2.4': 'x2',
        },
        columns: [
            ['x1', 'Building 1'],
            ['x2', 'Building 2'],
            ['Room 1.1', 15], // Building 1, Room 1
            ['Room 1.2', 30],
            ['Room 2.1', 10], // Building 2, Room 1
            ['Room 2.2', 20],
            ['Room 2.3', 15],
            ['Room 2.4', 20],
        ],
        type: 'bar',
        labels: true
    },
    axis: {
        x: {
            type: 'category',
        }
    }
});
```
I would expect to see 2 bars within category "Building 1" and 4 bars within category "Building 2". Currently (master branch) only one category "Building 1" is shown and it contains all 6 bars (http://jsfiddle.net/4qpprjrn/2/). 

I think this issue is not fully resolved and currently blocks me quite badly :(

**Comment by rlindner81** [comment]
@jnehlmeier It should be resolved when https://github.com/c3js/c3/pull/1689 is merged.

**Comment by jnehlmeier** [comment]
@rlindner81 Just tried it and it seems to fix the issue. However my example looks a bit unpleasant because bars are not centered within a category, see http://jsfiddle.net/4qpprjrn/4/ . Looks like the drawing routine still assumes 6 bars per category (instead of 2 & 4) and calculates horizontal bar positions based on that information.
